name: Cypress Tests

on: push

jobs:
  chrome-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.11.1-chrome-123.0.6312.58-1-ff-124.0-edge-122.0.2365.92-1
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          runTests: false
      - run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          command-prefix: 'percy exec -- npx'
          start: npm start
          wait-on: "http://localhost:8081"
          wait-on-timeout: 120
          browser: chrome
          spec: cypress/e2e/isolation/*
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

  firefox-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.11.1-chrome-123.0.6312.58-1-ff-124.0-edge-122.0.2365.92-1
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          runTests: false
      - run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          start: npm start
          wait-on: "http://localhost:8081"
          wait-on-timeout: 120
          browser: firefox
          spec: cypress/e2e/isolation/*

  edge-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.11.1-chrome-123.0.6312.58-1-ff-124.0-edge-122.0.2365.92-1
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          runTests: false
      - run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          start: npm start
          wait-on: "http://localhost:8081"
          wait-on-timeout: 120
          browser: edge
          spec: cypress/e2e/isolation/*
